//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMP.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMP.Portal.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start now.
        /// </summary>
        public static string btnStartNow {
            get {
                return ResourceManager.GetString("btnStartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you plan to grow any other crops in these fields?.
        /// </summary>
        public static string lbDoYouPlanToGrowAnyOtherCropsInTheseFields {
            get {
                return ResourceManager.GetString("lbDoYouPlanToGrowAnyOtherCropsInTheseFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a farm.
        /// </summary>
        public static string lblAddAFarm {
            get {
                return ResourceManager.GetString("lblAddAFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new farm.
        /// </summary>
        public static string lblAddANewFarm {
            get {
                return ResourceManager.GetString("lblAddANewFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another crop to this plan.
        /// </summary>
        public static string lblAddAnotherCrop {
            get {
                return ResourceManager.GetString("lblAddAnotherCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another field.
        /// </summary>
        public static string lblAddAnotherField {
            get {
                return ResourceManager.GetString("lblAddAnotherField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} addresses found.
        /// </summary>
        public static string lblAdddressFound {
            get {
                return ResourceManager.GetString("lblAdddressFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a field.
        /// </summary>
        public static string lblAddField {
            get {
                return ResourceManager.GetString("lblAddField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add fields for {0}.
        /// </summary>
        public static string lblAddFieldFor {
            get {
                return ResourceManager.GetString("lblAddFieldFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add manures to this plan.
        /// </summary>
        public static string lblAddManuresToThisPlan {
            get {
                return ResourceManager.GetString("lblAddManuresToThisPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addresses found.
        /// </summary>
        public static string lblAddressFoundCondition {
            get {
                return ResourceManager.GetString("lblAddressFoundCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1.
        /// </summary>
        public static string lblAddressLine1 {
            get {
                return ResourceManager.GetString("lblAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2 (optional).
        /// </summary>
        public static string lblAddressLine2 {
            get {
                return ResourceManager.GetString("lblAddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add soil analysis for {0}.
        /// </summary>
        public static string lblAddSoilAnalysis {
            get {
                return ResourceManager.GetString("lblAddSoilAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add soil nutrient value.
        /// </summary>
        public static string lblAddSoilNutrientValue {
            get {
                return ResourceManager.GetString("lblAddSoilNutrientValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the soil analysis for {0}.
        /// </summary>
        public static string lblAddTheSoilAnalysisFor {
            get {
                return ResourceManager.GetString("lblAddTheSoilAnalysisFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this farm.
        /// </summary>
        public static string lblAddThisFarm {
            get {
                return ResourceManager.GetString("lblAddThisFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this field.
        /// </summary>
        public static string lblAddThisField {
            get {
                return ResourceManager.GetString("lblAddThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add your fields.
        /// </summary>
        public static string lblAddYourFields {
            get {
                return ResourceManager.GetString("lblAddYourFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All farms.
        /// </summary>
        public static string lblAllFarm {
            get {
                return ResourceManager.GetString("lblAllFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the fields are above 300m.
        /// </summary>
        public static string lblAllTheFieldsAreAbove300m {
            get {
                return ResourceManager.GetString("lblAllTheFieldsAreAbove300m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the fields are in an NVZ.
        /// </summary>
        public static string lblAllTheFieldsAreInAnNVZ {
            get {
                return ResourceManager.GetString("lblAllTheFieldsAreInAnNVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount.
        /// </summary>
        public static string lblAmount {
            get {
                return ResourceManager.GetString("lblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another crop.
        /// </summary>
        public static string lblAnotherCrop {
            get {
                return ResourceManager.GetString("lblAnotherCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan and record nutrient applications.
        /// </summary>
        public static string lblApplicationName {
            get {
                return ResourceManager.GetString("lblApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to area.
        /// </summary>
        public static string lblArea {
            get {
                return ResourceManager.GetString("lblArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As an index.
        /// </summary>
        public static string lblAsAnIndex {
            get {
                return ResourceManager.GetString("lblAsAnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average annual rainfall.
        /// </summary>
        public static string lblAverageAnnualRainfall {
            get {
                return ResourceManager.GetString("lblAverageAnnualRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average annual rainfall for {0}.
        /// </summary>
        public static string lblAverageAnnualRainfallFor {
            get {
                return ResourceManager.GetString("lblAverageAnnualRainfallFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AverageAltitude.
        /// </summary>
        public static string lblAvgAtitude {
            get {
                return ResourceManager.GetString("lblAvgAtitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string lblBack {
            get {
                return ResourceManager.GetString("lblBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on a recent soil nitrogen analysis.
        /// </summary>
        public static string lblBasedOnARecentSoilNitrogenAnalysis {
            get {
                return ResourceManager.GetString("lblBasedOnARecentSoilNitrogenAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate based on a recent soil mineral nitrogen analysis result.
        /// </summary>
        public static string lblBasedOnRecentSNA {
            get {
                return ResourceManager.GetString("lblBasedOnRecentSNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on the previous crop.
        /// </summary>
        public static string lblBasedOnThePreviousCrop {
            get {
                return ResourceManager.GetString("lblBasedOnThePreviousCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        public static string lblBusinessName {
            get {
                return ResourceManager.GetString("lblBusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string lblChange {
            get {
                return ResourceManager.GetString("lblChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change this {0} plan.
        /// </summary>
        public static string lblChangeThisPlan {
            get {
                return ResourceManager.GetString("lblChangeThisPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change this postcode.
        /// </summary>
        public static string lblChangeThisPostcode {
            get {
                return ResourceManager.GetString("lblChangeThisPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your answers.
        /// </summary>
        public static string lblCheckYourAnswers {
            get {
                return ResourceManager.GetString("lblCheckYourAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string lblContinue {
            get {
                return ResourceManager.GetString("lblContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Crown copyright.
        /// </summary>
        public static string lblCopyRight {
            get {
                return ResourceManager.GetString("lblCopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        public static string lblCounty {
            get {
                return ResourceManager.GetString("lblCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPH.
        /// </summary>
        public static string lblCPHnumber {
            get {
                return ResourceManager.GetString("lblCPHnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a crop nutrient management plan.
        /// </summary>
        public static string lblCreateACropNutrientManagementPlan {
            get {
                return ResourceManager.GetString("lblCreateACropNutrientManagementPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a nutrient management plan.
        /// </summary>
        public static string lblCreateANutrientManagementPlan {
            get {
                return ResourceManager.GetString("lblCreateANutrientManagementPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create plan.
        /// </summary>
        public static string lblCreatePlan {
            get {
                return ResourceManager.GetString("lblCreatePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Group.
        /// </summary>
        public static string lblCropGroup {
            get {
                return ResourceManager.GetString("lblCropGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which crop group would you like to plan for?.
        /// </summary>
        public static string lblCropGroupForPlan {
            get {
                return ResourceManager.GetString("lblCropGroupForPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop info 1.
        /// </summary>
        public static string lblCropInfoOne {
            get {
                return ResourceManager.GetString("lblCropInfoOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop info two.
        /// </summary>
        public static string lblCropInfoTwo {
            get {
                return ResourceManager.GetString("lblCropInfoTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cropped area (optional).
        /// </summary>
        public static string lblCroppedArea {
            get {
                return ResourceManager.GetString("lblCroppedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cropped area.
        /// </summary>
        public static string lblCroppedAreaForCheckAnswere {
            get {
                return ResourceManager.GetString("lblCroppedAreaForCheckAnswere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop plan for {0}.
        /// </summary>
        public static string lblCropPlanFor {
            get {
                return ResourceManager.GetString("lblCropPlanFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Type.
        /// </summary>
        public static string lblCropType {
            get {
                return ResourceManager.GetString("lblCropType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which crop type would you like to plan for?.
        /// </summary>
        public static string lblCropTypeForPlan {
            get {
                return ResourceManager.GetString("lblCropTypeForPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current fields.
        /// </summary>
        public static string lblCurrentFields {
            get {
                return ResourceManager.GetString("lblCurrentFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When was the soil sample taken?.
        /// </summary>
        public static string lblDateSampleTaken {
            get {
                return ResourceManager.GetString("lblDateSampleTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does this field contain potash-releasing clay?.
        /// </summary>
        public static string lblDoesPotashClayForCheckAnswere {
            get {
                return ResourceManager.GetString("lblDoesPotashClayForCheckAnswere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a date for when you planted your {0} , or when you will plant it?.
        /// </summary>
        public static string lblDoYouHaveADateForWhenYouPlantedYour {
            get {
                return ResourceManager.GetString("lblDoYouHaveADateForWhenYouPlantedYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Rules.
        /// </summary>
        public static string lblEnglishRules {
            get {
                return ResourceManager.GetString("lblEnglishRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address manually.
        /// </summary>
        public static string lblEnterAddressManually {
            get {
                return ResourceManager.GetString("lblEnterAddressManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a single figure for all these fields.
        /// </summary>
        public static string lblEnterASingleFigureForAllTheseFields {
            get {
                return ResourceManager.GetString("lblEnterASingleFigureForAllTheseFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the average annual rainfall in millimetres for {0}.
        /// </summary>
        public static string lblEnterAverageAnualRainfall {
            get {
                return ResourceManager.GetString("lblEnterAverageAnualRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter different figures for each field.
        /// </summary>
        public static string lblEnterDifferentFiguresForEachField {
            get {
                return ResourceManager.GetString("lblEnterDifferentFiguresForEachField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not valid for {1}..
        /// </summary>
        public static string lblEnterNumericValue {
            get {
                return ResourceManager.GetString("lblEnterNumericValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the planting date for {0} in these fields?.
        /// </summary>
        public static string lblEnterSingleDateForAllField {
            get {
                return ResourceManager.GetString("lblEnterSingleDateForAllField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address for {0}.
        /// </summary>
        public static string lblEnterTheAddressFor {
            get {
                return ResourceManager.GetString("lblEnterTheAddressFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter the address manually.
        /// </summary>
        public static string lblEnterTheAddressManually {
            get {
                return ResourceManager.GetString("lblEnterTheAddressManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the crop name.
        /// </summary>
        public static string lblEnterTheCropName {
            get {
                return ResourceManager.GetString("lblEnterTheCropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string lblError {
            get {
                return ResourceManager.GetString("lblError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter farm name.
        /// </summary>
        public static string lblErrorMsgForFarmName {
            get {
                return ResourceManager.GetString("lblErrorMsgForFarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate based on previous cropping, soil type, and average rainfall.
        /// </summary>
        public static string lblEstimateBasedOnPreviousCrop {
            get {
                return ResourceManager.GetString("lblEstimateBasedOnPreviousCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string lblFalse {
            get {
                return ResourceManager.GetString("lblFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm Address.
        /// </summary>
        public static string lblFarmAddress {
            get {
                return ResourceManager.GetString("lblFarmAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm and field details.
        /// </summary>
        public static string lblFarmAndFieldDetails {
            get {
                return ResourceManager.GetString("lblFarmAndFieldDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainfall.
        /// </summary>
        public static string lblFarmAvgAnnualRainfall {
            get {
                return ResourceManager.GetString("lblFarmAvgAnnualRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Answer.
        /// </summary>
        public static string lblFarmCheck {
            get {
                return ResourceManager.GetString("lblFarmCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmers Name.
        /// </summary>
        public static string lblFarmersName {
            get {
                return ResourceManager.GetString("lblFarmersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} fields.
        /// </summary>
        public static string lblFarmFields {
            get {
                return ResourceManager.GetString("lblFarmFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm List.
        /// </summary>
        public static string lblFarmList {
            get {
                return ResourceManager.GetString("lblFarmList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm Name.
        /// </summary>
        public static string lblFarmName {
            get {
                return ResourceManager.GetString("lblFarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STD.
        /// </summary>
        public static string lblFarmSTDcode {
            get {
                return ResourceManager.GetString("lblFarmSTDcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FarmSummary.
        /// </summary>
        public static string lblFarmSummary {
            get {
                return ResourceManager.GetString("lblFarmSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string lblField {
            get {
                return ResourceManager.GetString("lblField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field and soil details.
        /// </summary>
        public static string lblFieldAndSoilDetails {
            get {
                return ResourceManager.GetString("lblFieldAndSoilDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field area.
        /// </summary>
        public static string lblFieldArea {
            get {
                return ResourceManager.GetString("lblFieldArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field measurements for {0}.
        /// </summary>
        public static string lblFieldMeasurements {
            get {
                return ResourceManager.GetString("lblFieldMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name.
        /// </summary>
        public static string lblFieldName {
            get {
                return ResourceManager.GetString("lblFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many fields at {0} are more than 300 metres above sea level?.
        /// </summary>
        public static string lblFieldsAbove300SeaLevel {
            get {
                return ResourceManager.GetString("lblFieldsAbove300SeaLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field(s).
        /// </summary>
        public static string lblFieldsCount {
            get {
                return ResourceManager.GetString("lblFieldsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First crop.
        /// </summary>
        public static string lblFirstCrop {
            get {
                return ResourceManager.GetString("lblFirstCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First crop group.
        /// </summary>
        public static string lblFirstCropGroup {
            get {
                return ResourceManager.GetString("lblFirstCropGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest Year.
        /// </summary>
        public static string lblHarvestYear {
            get {
                return ResourceManager.GetString("lblHarvestYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest Year Overview.
        /// </summary>
        public static string lblHarvestYearOverview {
            get {
                return ResourceManager.GetString("lblHarvestYearOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you planted your {0} yet?.
        /// </summary>
        public static string lblHaveYouPlantedYourCrop {
            get {
                return ResourceManager.GetString("lblHaveYouPlantedYourCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hectares.
        /// </summary>
        public static string lblHectares {
            get {
                return ResourceManager.GetString("lblHectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help protect the environment.
        /// </summary>
        public static string lblHelpProtectTheEnvironment {
            get {
                return ResourceManager.GetString("lblHelpProtectTheEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help you comply with environmental regulations.
        /// </summary>
        public static string lblHelpYouComplyWithEnvironmentalRegulations {
            get {
                return ResourceManager.GetString("lblHelpYouComplyWithEnvironmentalRegulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string lblHomePage {
            get {
                return ResourceManager.GetString("lblHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you plan to use the straw from these fields?.
        /// </summary>
        public static string lblHowDoYouPlanToUseTheStrawFromTheseFields {
            get {
                return ResourceManager.GetString("lblHowDoYouPlanToUseTheStrawFromTheseFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you want to enter the expected yield?.
        /// </summary>
        public static string lblHowDoYouWantToEnterExpectedYield {
            get {
                return ResourceManager.GetString("lblHowDoYouWantToEnterExpectedYield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you want to enter the expected yield for {0} in these fields?.
        /// </summary>
        public static string lblHowDoYouWantToEnterTheExpectedYieldForInTheseFields {
            get {
                return ResourceManager.GetString("lblHowDoYouWantToEnterTheExpectedYieldForInTheseFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many fields at {0}
        ///are in a Nitrate Vulnerable Zone (NVZ)?.
        /// </summary>
        public static string lblHowManyFieldsInNVZ {
            get {
                return ResourceManager.GetString("lblHowManyFieldsInNVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to calculate the soil nitrogen supply for {0}?.
        /// </summary>
        public static string lblHowWouldYouLikeToCalculateSNS {
            get {
                return ResourceManager.GetString("lblHowWouldYouLikeToCalculateSNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to calculate the soil nitrogen supply.
        /// </summary>
        public static string lblHowWouldYouLikeToCalculateSNSForCheckAnswer {
            get {
                return ResourceManager.GetString("lblHowWouldYouLikeToCalculateSNSForCheckAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to enter your soil nutrient values?.
        /// </summary>
        public static string lblHowWouldYouLikeToEnterYourSoilNutrientValues {
            get {
                return ResourceManager.GetString("lblHowWouldYouLikeToEnterYourSoilNutrientValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have more than one holding, it&apos;s best to add a separate farm for each..
        /// </summary>
        public static string lblIfYouhaveMoreThanOneHolding {
            get {
                return ResourceManager.GetString("lblIfYouhaveMoreThanOneHolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index values.
        /// </summary>
        public static string lblIndexValues {
            get {
                return ResourceManager.GetString("lblIndexValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In milligrams per litre.
        /// </summary>
        public static string lblInMilligramsPerLitre {
            get {
                return ResourceManager.GetString("lblInMilligramsPerLitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is {0} more than 300 metres above sea level?.
        /// </summary>
        public static string lblIsAbove300SeaLevel {
            get {
                return ResourceManager.GetString("lblIsAbove300SeaLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is {0} in a Nitrate Vulnerable Zone (NVZ)?.
        /// </summary>
        public static string lblIsNVZField {
            get {
                return ResourceManager.GetString("lblIsNVZField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is sulphur (S) deficiency expected in the soil?.
        /// </summary>
        public static string lblIsSoilDeficientInSulphur {
            get {
                return ResourceManager.GetString("lblIsSoilDeficientInSulphur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the soil a potash-releasing clay?.
        /// </summary>
        public static string lblIsSoilPostashReleasingClay {
            get {
                return ResourceManager.GetString("lblIsSoilPostashReleasingClay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this field more than 300 metres above sea level?.
        /// </summary>
        public static string lblIsThisFieldAboveForFieldCheckAnswere {
            get {
                return ResourceManager.GetString("lblIsThisFieldAboveForFieldCheckAnswere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Parcel ID (optional).
        /// </summary>
        public static string lblLandParcelID {
            get {
                return ResourceManager.GetString("lblLandParcelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Parcel ID.
        /// </summary>
        public static string lblLandParcelIDForCheckAnswere {
            get {
                return ResourceManager.GetString("lblLandParcelIDForCheckAnswere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated: {0}.
        /// </summary>
        public static string lblLastUpdated {
            get {
                return ResourceManager.GetString("lblLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add soil analysis.
        /// </summary>
        public static string lbllblAddSoilAnalysisTitle {
            get {
                return ResourceManager.GetString("lbllblAddSoilAnalysisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All content is available under the.
        /// </summary>
        public static string lblLicenseText {
            get {
                return ResourceManager.GetString("lblLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , except where otherwise stated.
        /// </summary>
        public static string lblLicenseTextExtra {
            get {
                return ResourceManager.GetString("lblLicenseTextExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnesium.
        /// </summary>
        public static string lblMagnesium {
            get {
                return ResourceManager.GetString("lblMagnesium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnesium (Mg) index.
        /// </summary>
        public static string lblMagnesiumIndex {
            get {
                return ResourceManager.GetString("lblMagnesiumIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnesium (Mg) per litre of soil.
        /// </summary>
        public static string lblMagnesiumPerLitreOfSoil {
            get {
                return ResourceManager.GetString("lblMagnesiumPerLitreOfSoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Farm Fields.
        /// </summary>
        public static string lblManageFarmFields {
            get {
                return ResourceManager.GetString("lblManageFarmFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage field details and soil analysis.
        /// </summary>
        public static string lblManageFieldDetailsAndSoilAnalysis {
            get {
                return ResourceManager.GetString("lblManageFieldDetailsAndSoilAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Address.
        /// </summary>
        public static string lblManualAddress {
            get {
                return ResourceManager.GetString("lblManualAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manure non-spreading area (optional).
        /// </summary>
        public static string lblManureNonSpreadingArea {
            get {
                return ResourceManager.GetString("lblManureNonSpreadingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manure non-spreading area.
        /// </summary>
        public static string lblManureNonSpreadingAreaForCheckAnswere {
            get {
                return ResourceManager.GetString("lblManureNonSpreadingAreaForCheckAnswere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string lblMessage {
            get {
                return ResourceManager.GetString("lblMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric Units.
        /// </summary>
        public static string lblMetricUnits {
            get {
                return ResourceManager.GetString("lblMetricUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg/l.
        /// </summary>
        public static string lblMgL {
            get {
                return ResourceManager.GetString("lblMgL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milligram values.
        /// </summary>
        public static string lblMiligramValues {
            get {
                return ResourceManager.GetString("lblMiligramValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string lblmm {
            get {
                return ResourceManager.GetString("lblmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Grid Reference (optional).
        /// </summary>
        public static string lblNationalGridReference {
            get {
                return ResourceManager.GetString("lblNationalGridReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Grid Reference.
        /// </summary>
        public static string lblNationalGridReferenceForCheckAnswere {
            get {
                return ResourceManager.GetString("lblNationalGridReferenceForCheckAnswere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I&apos;ll enter the date later.
        /// </summary>
        public static string lblNoIWillEnterTheDateLater {
            get {
                return ResourceManager.GetString("lblNoIWillEnterTheDateLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the fields are above 300m.
        /// </summary>
        public static string lblNoneOfTheFieldsAreAbove300m {
            get {
                return ResourceManager.GetString("lblNoneOfTheFieldsAreAbove300m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the fields are in an NVZ.
        /// </summary>
        public static string lblNoneOfTheFieldsAreInAnNVZ {
            get {
                return ResourceManager.GetString("lblNoneOfTheFieldsAreInAnNVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        public static string lblNotSet {
            get {
                return ResourceManager.GetString("lblNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to enter your soil nutrient values?.
        /// </summary>
        public static string lblNutrientValueTypeForCheckAnswere {
            get {
                return ResourceManager.GetString("lblNutrientValueTypeForCheckAnswere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVZ.
        /// </summary>
        public static string lblNVZ {
            get {
                return ResourceManager.GetString("lblNVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many fields at Oaktree Lane Farm are in a Nitrate Vulnerable Zone (NVZ).
        /// </summary>
        public static string lblNVZField {
            get {
                return ResourceManager.GetString("lblNVZField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this field inside a Nitrate Vulnerable Zone (NVZ)?.
        /// </summary>
        public static string lblNVZFieldForFieldCheckAnswere {
            get {
                return ResourceManager.GetString("lblNVZFieldForFieldCheckAnswere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Government Licence v3.0.
        /// </summary>
        public static string lblOpenGovernmentLicence {
            get {
                return ResourceManager.GetString("lblOpenGovernmentLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string lblOr {
            get {
                return ResourceManager.GetString("lblOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organic.
        /// </summary>
        public static string lblOrganic {
            get {
                return ResourceManager.GetString("lblOrganic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other reference (optional).
        /// </summary>
        public static string lblOtherReference {
            get {
                return ResourceManager.GetString("lblOtherReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Reference.
        /// </summary>
        public static string lblOtherReferenceForCheckAnswere {
            get {
                return ResourceManager.GetString("lblOtherReferenceForCheckAnswere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphate.
        /// </summary>
        public static string lblPhosphate {
            get {
                return ResourceManager.GetString("lblPhosphate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the phosphorus (P) analysis type?.
        /// </summary>
        public static string lblPhosphorusAnalysisType {
            get {
                return ResourceManager.GetString("lblPhosphorusAnalysisType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphorus (P) index.
        /// </summary>
        public static string lblPhosphorusIndex {
            get {
                return ResourceManager.GetString("lblPhosphorusIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphorus (P) per litre of soil.
        /// </summary>
        public static string lblPhosphorusPerLitreOfSoil {
            get {
                return ResourceManager.GetString("lblPhosphorusPerLitreOfSoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan and record nutrient applications.
        /// </summary>
        public static string lblPlanAndRecordNutrient_applications {
            get {
                return ResourceManager.GetString("lblPlanAndRecordNutrient applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan and record nutrient applications.
        /// </summary>
        public static string lblPlanAndRecordNutrientApplications {
            get {
                return ResourceManager.GetString("lblPlanAndRecordNutrientApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan created.
        /// </summary>
        public static string lblPlanCreated {
            get {
                return ResourceManager.GetString("lblPlanCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning and recording can:.
        /// </summary>
        public static string lblPlanningAndRecordingCan {
            get {
                return ResourceManager.GetString("lblPlanningAndRecordingCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans and records.
        /// </summary>
        public static string lblPlansAndRecords {
            get {
                return ResourceManager.GetString("lblPlansAndRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter {0}.
        /// </summary>
        public static string lblPleaseEnter {
            get {
                return ResourceManager.GetString("lblPleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string lblPostCode {
            get {
                return ResourceManager.GetString("lblPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potash.
        /// </summary>
        public static string lblPotash {
            get {
                return ResourceManager.GetString("lblPotash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potassium (K) index.
        /// </summary>
        public static string lblPotassiumIndex {
            get {
                return ResourceManager.GetString("lblPotassiumIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potassium (K) per litre of soil.
        /// </summary>
        public static string lblPotassiumPerLitreOfSoil {
            get {
                return ResourceManager.GetString("lblPotassiumPerLitreOfSoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  potato .
        /// </summary>
        public static string lblPotato {
            get {
                return ResourceManager.GetString("lblPotato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which potato variety group are you planning to grow?.
        /// </summary>
        public static string lblPotatoForCropType {
            get {
                return ResourceManager.GetString("lblPotatoForCropType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which fields do you plan to grow {0} potato in?.
        /// </summary>
        public static string lblPotatoForField {
            get {
                return ResourceManager.GetString("lblPotatoForField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainfall.
        /// </summary>
        public static string lblRainfall {
            get {
                return ResourceManager.GetString("lblRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainfall Manual.
        /// </summary>
        public static string lblRainfallManual {
            get {
                return ResourceManager.GetString("lblRainfallManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a registered organic producer?.
        /// </summary>
        public static string lblRegisteredOrganicProducer {
            get {
                return ResourceManager.GetString("lblRegisteredOrganicProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisteredOrganicProducer.
        /// </summary>
        public static string lblRegOrganicProducer {
            get {
                return ResourceManager.GetString("lblRegOrganicProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save you money.
        /// </summary>
        public static string lblSaveYouMoney {
            get {
                return ResourceManager.GetString("lblSaveYouMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SBI.
        /// </summary>
        public static string lblSBI {
            get {
                return ResourceManager.GetString("lblSBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second crop.
        /// </summary>
        public static string lblSecondCrop {
            get {
                return ResourceManager.GetString("lblSecondCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string lblSelectAll {
            get {
                return ResourceManager.GetString("lblSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all that apply..
        /// </summary>
        public static string lblSelectAllThatApply {
            get {
                return ResourceManager.GetString("lblSelectAllThatApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one option.
        /// </summary>
        public static string lblSelectOneOption {
            get {
                return ResourceManager.GetString("lblSelectOneOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the address for {0}.
        /// </summary>
        public static string lblSelectTheAddressFor {
            get {
                return ResourceManager.GetString("lblSelectTheAddressFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the crop information that is applicable.
        /// </summary>
        public static string lblSelectTheCropInformationThatIsApplicable {
            get {
                return ResourceManager.GetString("lblSelectTheCropInformationThatIsApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the farm address.
        /// </summary>
        public static string lblSelectTheFarmAddress {
            get {
                return ResourceManager.GetString("lblSelectTheFarmAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string lblSignout {
            get {
                return ResourceManager.GetString("lblSignout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the soil deficient in sulphur (S)?.
        /// </summary>
        public static string lblSoilDeficientInSulpurForCheckAnswer {
            get {
                return ResourceManager.GetString("lblSoilDeficientInSulpurForCheckAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil nutrient value Type.
        /// </summary>
        public static string lblSoilNutrientValueType {
            get {
                return ResourceManager.GetString("lblSoilNutrientValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil pH level.
        /// </summary>
        public static string lblSoilPHLevel {
            get {
                return ResourceManager.GetString("lblSoilPHLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil Releasing Clay.
        /// </summary>
        public static string lblSoilReleasingClay {
            get {
                return ResourceManager.GetString("lblSoilReleasingClay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil Type.
        /// </summary>
        public static string lblSoilType {
            get {
                return ResourceManager.GetString("lblSoilType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil type.
        /// </summary>
        public static string lblSoilTypeForCheckAnswer {
            get {
                return ResourceManager.GetString("lblSoilTypeForCheckAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the fields are above 300m.
        /// </summary>
        public static string lblSomeOfTheFieldsAreAbove300m {
            get {
                return ResourceManager.GetString("lblSomeOfTheFieldsAreAbove300m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the fields are in an NVZ.
        /// </summary>
        public static string lblSomeOfTheFieldsAreInAnNVZ {
            get {
                return ResourceManager.GetString("lblSomeOfTheFieldsAreInAnNVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sowing date.
        /// </summary>
        public static string lblSowingDate {
            get {
                return ResourceManager.GetString("lblSowingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SowingDate.
        /// </summary>
        public static string lblSowingDateForError {
            get {
                return ResourceManager.GetString("lblSowingDateForError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sowing date question.
        /// </summary>
        public static string lblSowingDateQuestion {
            get {
                return ResourceManager.GetString("lblSowingDateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulpher Deficient.
        /// </summary>
        public static string lblSulpherDeficient {
            get {
                return ResourceManager.GetString("lblSulpherDeficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the crops you grow.
        /// </summary>
        public static string lblTheCropsYouGrow {
            get {
                return ResourceManager.GetString("lblTheCropsYouGrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the manures and fertilisers you use and how you apply them.
        /// </summary>
        public static string lblTheManuresAndFertilisersYouUseAndHowYouApplyThem {
            get {
                return ResourceManager.GetString("lblTheManuresAndFertilisersYouUseAndHowYouApplyThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the nutrients in your soil.
        /// </summary>
        public static string lblTheNutrientsInYourSoil {
            get {
                return ResourceManager.GetString("lblTheNutrientsInYourSoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} fields in this plan.
        /// </summary>
        public static string lblThereAreFieldsInThisPlan {
            get {
                return ResourceManager.GetString("lblThereAreFieldsInThisPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tonnes/hectare.
        /// </summary>
        public static string lblTonnesAndHectare {
            get {
                return ResourceManager.GetString("lblTonnesAndHectare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To start creating plans and records,.
        /// </summary>
        public static string lblToStartCreatingPlanAndRecords {
            get {
                return ResourceManager.GetString("lblToStartCreatingPlanAndRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalFarmArea.
        /// </summary>
        public static string lblTotalFarmArea {
            get {
                return ResourceManager.GetString("lblTotalFarmArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total field area.
        /// </summary>
        public static string lblTotalFieldArea {
            get {
                return ResourceManager.GetString("lblTotalFieldArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town or city.
        /// </summary>
        public static string lblTownOrCity {
            get {
                return ResourceManager.GetString("lblTownOrCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string lblTrue {
            get {
                return ResourceManager.GetString("lblTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update farm details.
        /// </summary>
        public static string lblUpdateFarmDetails {
            get {
                return ResourceManager.GetString("lblUpdateFarmDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update fields or soil analysis.
        /// </summary>
        public static string lblUpdateFieldsOrSoilAnalysis {
            get {
                return ResourceManager.GetString("lblUpdateFieldsOrSoilAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the standard figure of 8 tonnes per hectare for all these fields.
        /// </summary>
        public static string lblUseTheStandardFigureOf8TonnesPerHectareForAllTheseFields {
            get {
                return ResourceManager.GetString("lblUseTheStandardFigureOf8TonnesPerHectareForAllTheseFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this service to plan and record how you use nutrients on your farm..
        /// </summary>
        public static string lblUseThisServiceToPlan {
            get {
                return ResourceManager.GetString("lblUseThisServiceToPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variety name.
        /// </summary>
        public static string lblVarietyName {
            get {
                return ResourceManager.GetString("lblVarietyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the variety name (optional)?.
        /// </summary>
        public static string lblVarietyNameWithOptional {
            get {
                return ResourceManager.GetString("lblVarietyNameWithOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View recommendations.
        /// </summary>
        public static string lblViewRecommendations {
            get {
                return ResourceManager.GetString("lblViewRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find any addresses for  {0}.
        /// </summary>
        public static string lblWeCouldNotFindAnyAddressesFor {
            get {
                return ResourceManager.GetString("lblWeCouldNotFindAnyAddressesFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the expected yield for {0} per hectare in these fields?.
        /// </summary>
        public static string lblWhatIsExpectedYieldForFields {
            get {
                return ResourceManager.GetString("lblWhatIsExpectedYieldForFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the length of growing season for Maris Piper potato?.
        /// </summary>
        public static string lblWhatIsLengthOfGrowingSeasonForCrop {
            get {
                return ResourceManager.GetString("lblWhatIsLengthOfGrowingSeasonForCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the soil type in {0}?.
        /// </summary>
        public static string lblWhatIsSoilType {
            get {
                return ResourceManager.GetString("lblWhatIsSoilType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the sowing date for {0} in these fields?.
        /// </summary>
        public static string lblWhatIsSowingDateinFields {
            get {
                return ResourceManager.GetString("lblWhatIsSowingDateinFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the current crop group?.
        /// </summary>
        public static string lblWhatIsTheCurrentCropGroup {
            get {
                return ResourceManager.GetString("lblWhatIsTheCurrentCropGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the current crop type?.
        /// </summary>
        public static string lblWhatIsTheCurrentCropType {
            get {
                return ResourceManager.GetString("lblWhatIsTheCurrentCropType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the expected yield for {0} in {1}?.
        /// </summary>
        public static string lblWhatIsTheDifferentExpectedYield {
            get {
                return ResourceManager.GetString("lblWhatIsTheDifferentExpectedYield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the expected yield for {0} in these fields?.
        /// </summary>
        public static string lblWhatIsTheExpectedYieldForSingle {
            get {
                return ResourceManager.GetString("lblWhatIsTheExpectedYieldForSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the farm name?.
        /// </summary>
        public static string lblWhatIsTheFarmName {
            get {
                return ResourceManager.GetString("lblWhatIsTheFarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the farm postcode?.
        /// </summary>
        public static string lblWhatIsTheFarmPostcode {
            get {
                return ResourceManager.GetString("lblWhatIsTheFarmPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the name of the crop?.
        /// </summary>
        public static string lblWhatIsTheNameOfTheCrop {
            get {
                return ResourceManager.GetString("lblWhatIsTheNameOfTheCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the planting date for {0} in {1}?.
        /// </summary>
        public static string lblWhatIsThePlantingDate {
            get {
                return ResourceManager.GetString("lblWhatIsThePlantingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the previous crop group?.
        /// </summary>
        public static string lblWhatWasThePreviousCropGroup {
            get {
                return ResourceManager.GetString("lblWhatWasThePreviousCropGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous crop group.
        /// </summary>
        public static string lblWhatWasThePreviousCropGroupForCheckAnswere {
            get {
                return ResourceManager.GetString("lblWhatWasThePreviousCropGroupForCheckAnswere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the previous crop type?.
        /// </summary>
        public static string lblWhatWasThePreviousCropType {
            get {
                return ResourceManager.GetString("lblWhatWasThePreviousCropType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous crop type.
        /// </summary>
        public static string lblWhatWasThePreviousCropTypeForCheckAnswere {
            get {
                return ResourceManager.GetString("lblWhatWasThePreviousCropTypeForCheckAnswere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which fields do you plan to grow {0} in?.
        /// </summary>
        public static string lblWhichFieldsDoYouPlanToGrow {
            get {
                return ResourceManager.GetString("lblWhichFieldsDoYouPlanToGrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which harvest would you like to plan for?.
        /// </summary>
        public static string lblWhichHarvestWouldYouLikeToPlanFor {
            get {
                return ResourceManager.GetString("lblWhichHarvestWouldYouLikeToPlanFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which variety name would you like to plan for?.
        /// </summary>
        public static string lblWhichVarietyNameWouldYouLikeToPlanFor {
            get {
                return ResourceManager.GetString("lblWhichVarietyNameWouldYouLikeToPlanFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I have a single date for all these fields.
        /// </summary>
        public static string lblYesIHaveASingleDateForAllTheseFields {
            get {
                return ResourceManager.GetString("lblYesIHaveASingleDateForAllTheseFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I have different dates for each of these fields.
        /// </summary>
        public static string lblYesIHaveDifferentDatesForEachOfTheseFields {
            get {
                return ResourceManager.GetString("lblYesIHaveDifferentDatesForEachOfTheseFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield.
        /// </summary>
        public static string lblYield {
            get {
                return ResourceManager.GetString("lblYield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield question.
        /// </summary>
        public static string lblYieldQuestion {
            get {
                return ResourceManager.GetString("lblYieldQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change your planting date later..
        /// </summary>
        public static string lblYouCanChangeYourPlantingDateLater {
            get {
                return ResourceManager.GetString("lblYouCanChangeYourPlantingDateLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You have added {0}.
        /// </summary>
        public static string lblYouHaveAdded {
            get {
                return ResourceManager.GetString("lblYouHaveAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not added any farms..
        /// </summary>
        public static string lblYouHaveNotAddedAnyFarms {
            get {
                return ResourceManager.GetString("lblYouHaveNotAddedAnyFarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your estimated average annual rainfall. If you think this is wrong, you can change it now or later..
        /// </summary>
        public static string lblYourAverageAnualRainfall {
            get {
                return ResourceManager.GetString("lblYourAverageAnualRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your farms.
        /// </summary>
        public static string lblYourFarms {
            get {
                return ResourceManager.GetString("lblYourFarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your plan will be based on:.
        /// </summary>
        public static string lblYourPlanWillBasedOn {
            get {
                return ResourceManager.GetString("lblYourPlanWillBasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cropped area cannot be larger than the total field area.
        /// </summary>
        public static string MsgCroppedAreaIsGreaterThanTotalArea {
            get {
                return ResourceManager.GetString("MsgCroppedAreaIsGreaterThanTotalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, 27 3 2007.
        /// </summary>
        public static string MsgDateExample {
            get {
                return ResourceManager.GetString("MsgDateExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a real date.
        /// </summary>
        public static string MsgDateMustBeARealDate {
            get {
                return ResourceManager.GetString("MsgDateMustBeARealDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a county.
        /// </summary>
        public static string MsgEnterACounty {
            get {
                return ResourceManager.GetString("MsgEnterACounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a date after DD/MM/YYYY.
        /// </summary>
        public static string MsgEnterADateAfter {
            get {
                return ResourceManager.GetString("MsgEnterADateAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a date before continuing.
        /// </summary>
        public static string MsgEnterADateBeforeContinuing {
            get {
                return ResourceManager.GetString("MsgEnterADateBeforeContinuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address line 1, typically the building and street.
        /// </summary>
        public static string MsgEnterAddressLine1TypicallyTheBuildingAndSreet {
            get {
                return ResourceManager.GetString("MsgEnterAddressLine1TypicallyTheBuildingAndSreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an address.
        /// </summary>
        public static string MsgEnterAnAddress {
            get {
                return ResourceManager.GetString("MsgEnterAnAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a pH range between 0 and 9.9.
        /// </summary>
        public static string MsgEnterAPH {
            get {
                return ResourceManager.GetString("MsgEnterAPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a pH before continuing.
        /// </summary>
        public static string MsgEnterAPHBeforeContinuing {
            get {
                return ResourceManager.GetString("MsgEnterAPHBeforeContinuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a postcode.
        /// </summary>
        public static string MsgEnterAPostcode {
            get {
                return ResourceManager.GetString("MsgEnterAPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a town or city.
        /// </summary>
        public static string MsgEnterATownOrCity {
            get {
                return ResourceManager.GetString("MsgEnterATownOrCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid postcode.
        /// </summary>
        public static string MsgEnterAValidPostcode {
            get {
                return ResourceManager.GetString("MsgEnterAValidPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the average annual rainfall.
        /// </summary>
        public static string MsgEnterAverageAnnualRainfall {
            get {
                return ResourceManager.GetString("MsgEnterAverageAnnualRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the {0} only in numbers..
        /// </summary>
        public static string MsgEnterDataOnlyInNumber {
            get {
                return ResourceManager.GetString("MsgEnterDataOnlyInNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the area only in numbers.
        /// </summary>
        public static string MsgEnterNumericValue {
            get {
                return ResourceManager.GetString("MsgEnterNumericValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the average annual rainfall.
        /// </summary>
        public static string MsgEnterTheAverageAnnualRainfall {
            get {
                return ResourceManager.GetString("MsgEnterTheAverageAnnualRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the date in numbers. For example, 27 3 2007.
        /// </summary>
        public static string MsgEnterTheDateInNumber {
            get {
                return ResourceManager.GetString("MsgEnterTheDateInNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the farm name.
        /// </summary>
        public static string MsgEnterTheFarmName {
            get {
                return ResourceManager.GetString("MsgEnterTheFarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the farm postcode.
        /// </summary>
        public static string MsgEnterTheFarmPostcode {
            get {
                return ResourceManager.GetString("MsgEnterTheFarmPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the field name.
        /// </summary>
        public static string MsgEnterTheFieldName {
            get {
                return ResourceManager.GetString("MsgEnterTheFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the total field area.
        /// </summary>
        public static string MsgEnterTotalFieldArea {
            get {
                return ResourceManager.GetString("MsgEnterTotalFieldArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the valid annual rainfall.
        /// </summary>
        public static string MsgEnterValidAnnualRainfall {
            get {
                return ResourceManager.GetString("MsgEnterValidAnnualRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an amount between 0 and 9999kg.
        /// </summary>
        public static string MsgEnterValidValueForNutrient {
            get {
                return ResourceManager.GetString("MsgEnterValidValueForNutrient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an index between 0 and 9.
        /// </summary>
        public static string MsgEnterValidValueForNutrientIndex {
            get {
                return ResourceManager.GetString("MsgEnterValidValueForNutrientIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter yield before continue.
        /// </summary>
        public static string MsgEnterYield {
            get {
                return ResourceManager.GetString("MsgEnterYield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A farm with that name and postcode has already been added. You or someone else who works on the farm may have already added it..
        /// </summary>
        public static string MsgFarmAlreadyExist {
            get {
                return ResourceManager.GetString("MsgFarmAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a farm name that is no more than 250 characters long.
        /// </summary>
        public static string MsgFarmNameMinMaxValidation {
            get {
                return ResourceManager.GetString("MsgFarmNameMinMaxValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already added a field with that name. Enter a different field name..
        /// </summary>
        public static string MsgFieldAlreadyExist {
            get {
                return ResourceManager.GetString("MsgFieldAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The combined cropped area and manure non-spreading area cannot be larger than the total field area.
        /// </summary>
        public static string MsgIfCroppedAreaAndNonSpreadingArea {
            get {
                return ResourceManager.GetString("MsgIfCroppedAreaAndNonSpreadingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your soil nutrient values. As your soil sample is more than five years old, your crop need recommendations will be based on standard figures for your soil type..
        /// </summary>
        public static string MsgIfSampleDateIsFiveYearOld {
            get {
                return ResourceManager.GetString("MsgIfSampleDateIsFiveYearOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Land Parcel ID that is no more than 14 characters long.
        /// </summary>
        public static string MsgLandParcelIdMinMaxValidation {
            get {
                return ResourceManager.GetString("MsgLandParcelIdMinMaxValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the magnesium index before continuing.
        /// </summary>
        public static string MsgMagnesiumIndex {
            get {
                return ResourceManager.GetString("MsgMagnesiumIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnesium (Mg) per litre of soil not set.
        /// </summary>
        public static string MsgMagnesiumNotSet {
            get {
                return ResourceManager.GetString("MsgMagnesiumNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the amount of magnesium before continuing.
        /// </summary>
        public static string MsgMagnesiumPerLitreOfSoil {
            get {
                return ResourceManager.GetString("MsgMagnesiumPerLitreOfSoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manure non-spreading area cannot be larger than the total field area.
        /// </summary>
        public static string MsgManureNonSpreadingAreaIsGreaterThanTotalArea {
            get {
                return ResourceManager.GetString("MsgManureNonSpreadingAreaIsGreaterThanTotalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a National Grid Reference that is no more than 4 characters long.
        /// </summary>
        public static string MsgNationalGridReferenceMinMaxValidation {
            get {
                return ResourceManager.GetString("MsgNationalGridReferenceMinMaxValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phosphorus index before continuing.
        /// </summary>
        public static string MsgPhosphorusIndex {
            get {
                return ResourceManager.GetString("MsgPhosphorusIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phosphorus (P) per litre of soil not set.
        /// </summary>
        public static string MsgPhosphorusNotSet {
            get {
                return ResourceManager.GetString("MsgPhosphorusNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the amount of phosphorus before continuing.
        /// </summary>
        public static string MsgPhosphorusPerLitreOfSoil {
            get {
                return ResourceManager.GetString("MsgPhosphorusPerLitreOfSoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The postcode entered is in the wrong format..
        /// </summary>
        public static string MsgPostcodeEnteredInWrongFomat {
            get {
                return ResourceManager.GetString("MsgPostcodeEnteredInWrongFomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid postcode. Postcodes contain only letters and numbers and are between 6 and 8 characters long..
        /// </summary>
        public static string MsgPostcodeMinMaxValidation {
            get {
                return ResourceManager.GetString("MsgPostcodeMinMaxValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the potassium index before continuing.
        /// </summary>
        public static string MsgPotassiumIndex {
            get {
                return ResourceManager.GetString("MsgPotassiumIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potassium (K) per litre of soil not set.
        /// </summary>
        public static string MsgPotassiumNotSet {
            get {
                return ResourceManager.GetString("MsgPotassiumNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the amount of potassium before continuing.
        /// </summary>
        public static string MsgPotassiumPerLitreOfSoil {
            get {
                return ResourceManager.GetString("MsgPotassiumPerLitreOfSoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous crop type not set.
        /// </summary>
        public static string MsgPreviousCropTypeNotSet {
            get {
                return ResourceManager.GetString("MsgPreviousCropTypeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an address.
        /// </summary>
        public static string MsgSelectAddress {
            get {
                return ResourceManager.GetString("MsgSelectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a {0} before continuing.
        /// </summary>
        public static string MsgSelectANameOfFieldBeforeContinuing {
            get {
                return ResourceManager.GetString("MsgSelectANameOfFieldBeforeContinuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option before continuing.
        /// </summary>
        public static string MsgSelectAnOptionBeforeContinuing {
            get {
                return ResourceManager.GetString("MsgSelectAnOptionBeforeContinuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not available at this moment. Please try after some time..
        /// </summary>
        public static string MsgServiceNotAvailable {
            get {
                return ResourceManager.GetString("MsgServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potash-releasing clay not set.
        /// </summary>
        public static string MsgSoilReleasingClayNotSet {
            get {
                return ResourceManager.GetString("MsgSoilReleasingClayNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn’t add your field, please try again later.
        /// </summary>
        public static string MsgWeCouldNotAddYourFieldPleaseTryAgainLater {
            get {
                return ResourceManager.GetString("MsgWeCouldNotAddYourFieldPleaseTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn’t create your plan, please try again later.
        /// </summary>
        public static string MsgWeCouldNotCreateYourPlanPleaseTryAgainLater {
            get {
                return ResourceManager.GetString("MsgWeCouldNotCreateYourPlanPleaseTryAgainLater", resourceCulture);
            }
        }
    }
}
