//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMP.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMP.Portal.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a farm.
        /// </summary>
        public static string lblAddAFarm {
            get {
                return ResourceManager.GetString("lblAddAFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new farm.
        /// </summary>
        public static string lblAddANewFarm {
            get {
                return ResourceManager.GetString("lblAddANewFarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} addresses found.
        /// </summary>
        public static string lblAdddressFound {
            get {
                return ResourceManager.GetString("lblAdddressFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addresses found.
        /// </summary>
        public static string lblAddressFoundCondition {
            get {
                return ResourceManager.GetString("lblAddressFoundCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1.
        /// </summary>
        public static string lblAddressLine1 {
            get {
                return ResourceManager.GetString("lblAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2 (optional).
        /// </summary>
        public static string lblAddressLine2 {
            get {
                return ResourceManager.GetString("lblAddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the fields are above 300m.
        /// </summary>
        public static string lblAllTheFieldsAreAbove300m {
            get {
                return ResourceManager.GetString("lblAllTheFieldsAreAbove300m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the fields are in an NVZ.
        /// </summary>
        public static string lblAllTheFieldsAreInAnNVZ {
            get {
                return ResourceManager.GetString("lblAllTheFieldsAreInAnNVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan and record nutrient applications.
        /// </summary>
        public static string lblApplicationName {
            get {
                return ResourceManager.GetString("lblApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average annual rainfall.
        /// </summary>
        public static string lblAverageAnnualRainfall {
            get {
                return ResourceManager.GetString("lblAverageAnnualRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average annual rainfall for {0}.
        /// </summary>
        public static string lblAverageAnnualRainfallFor {
            get {
                return ResourceManager.GetString("lblAverageAnnualRainfallFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AverageAltitude.
        /// </summary>
        public static string lblAvgAtitude {
            get {
                return ResourceManager.GetString("lblAvgAtitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string lblBack {
            get {
                return ResourceManager.GetString("lblBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        public static string lblBusinessName {
            get {
                return ResourceManager.GetString("lblBusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string lblChange {
            get {
                return ResourceManager.GetString("lblChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change this postcode.
        /// </summary>
        public static string lblChangeThisPostcode {
            get {
                return ResourceManager.GetString("lblChangeThisPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string lblContinue {
            get {
                return ResourceManager.GetString("lblContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Crown copyright.
        /// </summary>
        public static string lblCopyRight {
            get {
                return ResourceManager.GetString("lblCopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        public static string lblCounty {
            get {
                return ResourceManager.GetString("lblCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPH.
        /// </summary>
        public static string lblCPHnumber {
            get {
                return ResourceManager.GetString("lblCPHnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Rules.
        /// </summary>
        public static string lblEnglishRules {
            get {
                return ResourceManager.GetString("lblEnglishRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address manually.
        /// </summary>
        public static string lblEnterAddressManually {
            get {
                return ResourceManager.GetString("lblEnterAddressManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the average annual rainfall in millimetres for {0}.
        /// </summary>
        public static string lblEnterAverageAnualRainfall {
            get {
                return ResourceManager.GetString("lblEnterAverageAnualRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the address for {0}.
        /// </summary>
        public static string lblEnterTheAddressFor {
            get {
                return ResourceManager.GetString("lblEnterTheAddressFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter the address manually.
        /// </summary>
        public static string lblEnterTheAddressManually {
            get {
                return ResourceManager.GetString("lblEnterTheAddressManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string lblError {
            get {
                return ResourceManager.GetString("lblError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter farm name.
        /// </summary>
        public static string lblErrorMsgForFarmName {
            get {
                return ResourceManager.GetString("lblErrorMsgForFarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string lblFalse {
            get {
                return ResourceManager.GetString("lblFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainfall.
        /// </summary>
        public static string lblFarmAvgAnnualRainfall {
            get {
                return ResourceManager.GetString("lblFarmAvgAnnualRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmers Name.
        /// </summary>
        public static string lblFarmersName {
            get {
                return ResourceManager.GetString("lblFarmersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm List.
        /// </summary>
        public static string lblFarmList {
            get {
                return ResourceManager.GetString("lblFarmList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm Name.
        /// </summary>
        public static string lblFarmName {
            get {
                return ResourceManager.GetString("lblFarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STD.
        /// </summary>
        public static string lblFarmSTDcode {
            get {
                return ResourceManager.GetString("lblFarmSTDcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many fields at {0} are more than 300 metres above sea level.
        /// </summary>
        public static string lblFieldsAbove300SeaLevel {
            get {
                return ResourceManager.GetString("lblFieldsAbove300SeaLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help protect the environment.
        /// </summary>
        public static string lblHelpProtectTheEnvironment {
            get {
                return ResourceManager.GetString("lblHelpProtectTheEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help you comply with environmental regulations.
        /// </summary>
        public static string lblHelpYouComplyWithEnvironmentalRegulations {
            get {
                return ResourceManager.GetString("lblHelpYouComplyWithEnvironmentalRegulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string lblHomePage {
            get {
                return ResourceManager.GetString("lblHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many fields at
        ///are in a Nitrate Vulnerable Zone (NVZ)?.
        /// </summary>
        public static string lblHowManyFieldsInNVZ {
            get {
                return ResourceManager.GetString("lblHowManyFieldsInNVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have more than one holding, it&apos;s best to add a separate farm for each..
        /// </summary>
        public static string lblIfYouhaveMoreThanOneHolding {
            get {
                return ResourceManager.GetString("lblIfYouhaveMoreThanOneHolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All content is available under the.
        /// </summary>
        public static string lblLicenseText {
            get {
                return ResourceManager.GetString("lblLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , except where otherwise stated.
        /// </summary>
        public static string lblLicenseTextExtra {
            get {
                return ResourceManager.GetString("lblLicenseTextExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Address.
        /// </summary>
        public static string lblManualAddress {
            get {
                return ResourceManager.GetString("lblManualAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string lblMessage {
            get {
                return ResourceManager.GetString("lblMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric Units.
        /// </summary>
        public static string lblMetricUnits {
            get {
                return ResourceManager.GetString("lblMetricUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string lblmm {
            get {
                return ResourceManager.GetString("lblmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the fields are above 300m.
        /// </summary>
        public static string lblNoneOfTheFieldsAreAbove300m {
            get {
                return ResourceManager.GetString("lblNoneOfTheFieldsAreAbove300m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the fields are in an NVZ.
        /// </summary>
        public static string lblNoneOfTheFieldsAreInAnNVZ {
            get {
                return ResourceManager.GetString("lblNoneOfTheFieldsAreInAnNVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVZ.
        /// </summary>
        public static string lblNVZ {
            get {
                return ResourceManager.GetString("lblNVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many fields at Oaktree Lane Farm are in a Nitrate Vulnerable Zone (NVZ).
        /// </summary>
        public static string lblNVZField {
            get {
                return ResourceManager.GetString("lblNVZField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Government Licence v3.0.
        /// </summary>
        public static string lblOpenGovernmentLicence {
            get {
                return ResourceManager.GetString("lblOpenGovernmentLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string lblOr {
            get {
                return ResourceManager.GetString("lblOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan and record nutrient applications.
        /// </summary>
        public static string lblPlanAndRecordNutrient_applications {
            get {
                return ResourceManager.GetString("lblPlanAndRecordNutrient applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan and record nutrient applications.
        /// </summary>
        public static string lblPlanAndRecordNutrientApplications {
            get {
                return ResourceManager.GetString("lblPlanAndRecordNutrientApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning and recording can:.
        /// </summary>
        public static string lblPlanningAndRecordingCan {
            get {
                return ResourceManager.GetString("lblPlanningAndRecordingCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter {0}.
        /// </summary>
        public static string lblPleaseEnter {
            get {
                return ResourceManager.GetString("lblPleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string lblPostCode {
            get {
                return ResourceManager.GetString("lblPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainfall.
        /// </summary>
        public static string lblRainfall {
            get {
                return ResourceManager.GetString("lblRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainfall Manual.
        /// </summary>
        public static string lblRainfallManual {
            get {
                return ResourceManager.GetString("lblRainfallManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistredOrganicProducer.
        /// </summary>
        public static string lblRegOrganicProducer {
            get {
                return ResourceManager.GetString("lblRegOrganicProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save you money.
        /// </summary>
        public static string lblSaveYouMoney {
            get {
                return ResourceManager.GetString("lblSaveYouMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SBI.
        /// </summary>
        public static string lblSBI {
            get {
                return ResourceManager.GetString("lblSBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the address for {0}.
        /// </summary>
        public static string lblSelectTheAddressFor {
            get {
                return ResourceManager.GetString("lblSelectTheAddressFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the farm address.
        /// </summary>
        public static string lblSelectTheFarmAddress {
            get {
                return ResourceManager.GetString("lblSelectTheFarmAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string lblSignout {
            get {
                return ResourceManager.GetString("lblSignout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the fields are above 300m.
        /// </summary>
        public static string lblSomeOfTheFieldsAreAbove300m {
            get {
                return ResourceManager.GetString("lblSomeOfTheFieldsAreAbove300m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the fields are in an NVZ.
        /// </summary>
        public static string lblSomeOfTheFieldsAreInAnNVZ {
            get {
                return ResourceManager.GetString("lblSomeOfTheFieldsAreInAnNVZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the crops you grow.
        /// </summary>
        public static string lblTheCropsYouGrow {
            get {
                return ResourceManager.GetString("lblTheCropsYouGrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the manures and fertilisers you use and how you apply them.
        /// </summary>
        public static string lblTheManuresAndFertilisersYouUseAndHowYouApplyThem {
            get {
                return ResourceManager.GetString("lblTheManuresAndFertilisersYouUseAndHowYouApplyThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the nutrients in your soil.
        /// </summary>
        public static string lblTheNutrientsInYourSoil {
            get {
                return ResourceManager.GetString("lblTheNutrientsInYourSoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalFarmArea.
        /// </summary>
        public static string lblTotalFarmArea {
            get {
                return ResourceManager.GetString("lblTotalFarmArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town or city.
        /// </summary>
        public static string lblTownOrCity {
            get {
                return ResourceManager.GetString("lblTownOrCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string lblTrue {
            get {
                return ResourceManager.GetString("lblTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this service to plan and record how you apply nutrients and fertilisers on your farm..
        /// </summary>
        public static string lblUseThisServiceToPlan {
            get {
                return ResourceManager.GetString("lblUseThisServiceToPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not find any addresses for  {0}.
        /// </summary>
        public static string lblWeCouldNotFindAnyAddressesFor {
            get {
                return ResourceManager.GetString("lblWeCouldNotFindAnyAddressesFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the farm name?.
        /// </summary>
        public static string lblWhatIsTheFarmName {
            get {
                return ResourceManager.GetString("lblWhatIsTheFarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the farm postcode?.
        /// </summary>
        public static string lblWhatIsTheFarmPostcode {
            get {
                return ResourceManager.GetString("lblWhatIsTheFarmPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not added any farms..
        /// </summary>
        public static string lblYouHaveNotAddedAnyFarms {
            get {
                return ResourceManager.GetString("lblYouHaveNotAddedAnyFarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your estimated average annual rainfall. If you think this is wrong, you can change it now or later..
        /// </summary>
        public static string lblYourAverageAnualRainfall {
            get {
                return ResourceManager.GetString("lblYourAverageAnualRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your farms.
        /// </summary>
        public static string lblYourFarms {
            get {
                return ResourceManager.GetString("lblYourFarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your plan will be based on:.
        /// </summary>
        public static string lblYourPlanWillBasedOn {
            get {
                return ResourceManager.GetString("lblYourPlanWillBasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a county.
        /// </summary>
        public static string MsgEnterACounty {
            get {
                return ResourceManager.GetString("MsgEnterACounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address line 1, typically the building and street.
        /// </summary>
        public static string MsgEnterAddressLine1TypicallyTheBuildingAndSreet {
            get {
                return ResourceManager.GetString("MsgEnterAddressLine1TypicallyTheBuildingAndSreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an address.
        /// </summary>
        public static string MsgEnterAnAddress {
            get {
                return ResourceManager.GetString("MsgEnterAnAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a postcode.
        /// </summary>
        public static string MsgEnterAPostcode {
            get {
                return ResourceManager.GetString("MsgEnterAPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a town or city.
        /// </summary>
        public static string MsgEnterATownOrCity {
            get {
                return ResourceManager.GetString("MsgEnterATownOrCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid postcode.
        /// </summary>
        public static string MsgEnterAValidPostcode {
            get {
                return ResourceManager.GetString("MsgEnterAValidPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the average annual rainfall.
        /// </summary>
        public static string MsgEnterAverageAnnualRainfall {
            get {
                return ResourceManager.GetString("MsgEnterAverageAnnualRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the average annual rainfall.
        /// </summary>
        public static string MsgEnterTheAverageAnnualRainfall {
            get {
                return ResourceManager.GetString("MsgEnterTheAverageAnnualRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the farm name.
        /// </summary>
        public static string MsgEnterTheFarmName {
            get {
                return ResourceManager.GetString("MsgEnterTheFarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the farm postcode.
        /// </summary>
        public static string MsgEnterTheFarmPostcode {
            get {
                return ResourceManager.GetString("MsgEnterTheFarmPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the valid annual rainfall.
        /// </summary>
        public static string MsgEnterValidAnnualRainfall {
            get {
                return ResourceManager.GetString("MsgEnterValidAnnualRainfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a farm name that is no more than 250 characters long.
        /// </summary>
        public static string MsgFarmNameMinMaxValidation {
            get {
                return ResourceManager.GetString("MsgFarmNameMinMaxValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The postcode entered is in the wrong format..
        /// </summary>
        public static string MsgPostcodeEnteredInWrongFomat {
            get {
                return ResourceManager.GetString("MsgPostcodeEnteredInWrongFomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid postcode. Postcodes contain only letters and numbers and are between 6 and 8 characters long..
        /// </summary>
        public static string MsgPostcodeMinMaxValidation {
            get {
                return ResourceManager.GetString("MsgPostcodeMinMaxValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an address.
        /// </summary>
        public static string MsgSelectAddress {
            get {
                return ResourceManager.GetString("MsgSelectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option before continuing.
        /// </summary>
        public static string MsgSelectAnOptionBeforeContinuing {
            get {
                return ResourceManager.GetString("MsgSelectAnOptionBeforeContinuing", resourceCulture);
            }
        }
    }
}
